name: luxe_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  file_picker: '>=8.1.2'
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_stripe: ^12.2.0
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.7
  google_sign_in: ^7.2.0
  http: ^1.6.0
  image_picker: '>=1.1.2'
  provider: ^6.1.5+1
  supabase_flutter: ^2.12.0
  url_launcher: ^6.3.2
  share_plus: ^10.0.0
  path_provider: ^2.1.3
  image_gallery_saver_plus: ^3.0.1+1
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  chewie: ^1.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/
